[package]
name = "rexpr"
version = "0.1.0"
authors = ["Subhranil Mukherjee <subhranilmukherjee190@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
